### ISSUE TITLE
on member edit page... let you set a user to be an organizer of one of your groups

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#395] opened 2017-11-03 15:41 UTC
As an organizer of a group editing a member record i should be able to make that person's role for the group to an organizer.

**Comment by Matt-Holland** [comment] 2017-11-10 15:01
this is a duplicate of existing ticket #391 . The other ticket has wireframes and more detail, I'm closing this one.

**Closed by Matt-Holland** 2017-11-10 15:01 UTC
Labels: enhancement, good first issue, help wanted
